### ISSUE TITLE
Fallback to monospace font  (text area)

### ISSUE THREAD

**Issue by jccsvq** [mmurak/SquareRootByHalfSquareWithKijoho#1]
Hello Masaaki,

Please add a fallback to monospace font in case the _Monaco_ font is not in the system. Otherwise the text appears in non-monospaced font and loses alignment.

For instance

```html
  <textarea id="displayArea" rows="25" cols="100" style="font-family:Monaco,  monospace"></textarea>
```
on line 16 of ```sqrtWithKijoho.html``` 
or leave it as in ```index.html```:

```html
  <textarea id="displayArea" rows="25" cols="100" style="font-family:Mono"></textarea>
```
By the way, I'm Jesus Cabrera, from the soroban/abacus group. 
Greetings,
Jesus

**Comment by mmurak** [comment]
Thanks for the issue.  I've just fixed the problem.  :-)
